SELECT object_name, object_type, status 
FROM USER_OBJECTS 
WHERE object_name IN (
    'INSERTARESTUDIANTE',
    'ACTUALIZARESTUDIANTE',
    'ACTUALIZARCORREOESTUDIANTE',
    'ELIMINARESTUDIANTE',
    'OBTENERESTUDIANTE',
    'LISTARESTUDIANTES',
    'BUSCARESTUDIANTES'
)
ORDER BY object_type, object_name;
