--------------------------------------------------------
--  File created - sábado-noviembre-08-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ESTUDIANTES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ESTUDIANTES" 
   (	"ID_ESTUDIANTE" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(60 BYTE), 
	"APELLIDO" VARCHAR2(60 BYTE), 
	"IDENTIFICACION" VARCHAR2(20 BYTE), 
	"CORREO" VARCHAR2(80 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ALERTASMOROSIDAD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ALERTASMOROSIDAD" 
   (	"ID_ALERTA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_ESTUDIANTE" NUMBER(*,0), 
	"FECHA_ALERTA" DATE DEFAULT CURRENT_DATE, 
	"DIAS_MORA" NUMBER(*,0), 
	"ESTADO_ALERTA" VARCHAR2(20 BYTE) DEFAULT 'Pendiente'
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ESTADOSFINANCIEROS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ESTADOSFINANCIEROS" 
   (	"ID_ESTADO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_ESTUDIANTE" NUMBER(*,0), 
	"SALDO_ACTUAL" NUMBER(10,2) DEFAULT 0, 
	"ULTIMA_ACTUALIZACION" DATE DEFAULT CURRENT_DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATRICULAS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MATRICULAS" 
   (	"ID_MATRICULA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_ESTUDIANTE" NUMBER(*,0), 
	"AÑO" NUMBER(*,0), 
	"CUATRIMESTRE" NUMBER(*,0), 
	"MONTO_TOTAL" NUMBER(10,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAGOS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PAGOS" 
   (	"ID_PAGO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_ESTUDIANTE" NUMBER(*,0), 
	"FECHA_PAGO" DATE, 
	"MONTO" NUMBER(10,2), 
	"METODO_PAGO" VARCHAR2(40 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'Procesado'
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ESTUDIANTES
SET DEFINE OFF;
REM INSERTING into SYSTEM.ALERTASMOROSIDAD
SET DEFINE OFF;
REM INSERTING into SYSTEM.ESTADOSFINANCIEROS
SET DEFINE OFF;
REM INSERTING into SYSTEM.MATRICULAS
SET DEFINE OFF;
REM INSERTING into SYSTEM.PAGOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008319
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008319" ON "SYSTEM"."ESTUDIANTES" ("ID_ESTUDIANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008320
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008320" ON "SYSTEM"."ESTUDIANTES" ("IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008341
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008341" ON "SYSTEM"."ALERTASMOROSIDAD" ("ID_ALERTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008336
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008336" ON "SYSTEM"."ESTADOSFINANCIEROS" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008326
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008326" ON "SYSTEM"."MATRICULAS" ("ID_MATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008332
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008332" ON "SYSTEM"."PAGOS" ("ID_PAGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_ACTUALIZAR_SALDO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_ACTUALIZAR_SALDO" 
AFTER INSERT ON Pagos
FOR EACH ROW
DECLARE
    v_saldo DECIMAL(10,2);
BEGIN
    v_saldo := CalcularSaldo(:NEW.ID_Estudiante);

    UPDATE EstadosFinancieros
    SET Saldo_Actual = v_saldo,
        Ultima_Actualizacion = CURRENT_DATE
    WHERE ID_Estudiante = :NEW.ID_Estudiante;
END;

/
ALTER TRIGGER "SYSTEM"."TRG_ACTUALIZAR_SALDO" ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ESTUDIANTES" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTUDIANTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTUDIANTES" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTUDIANTES" MODIFY ("IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTUDIANTES" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTUDIANTES" ADD PRIMARY KEY ("ID_ESTUDIANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ESTUDIANTES" ADD UNIQUE ("IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ALERTASMOROSIDAD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ALERTASMOROSIDAD" MODIFY ("ID_ALERTA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ALERTASMOROSIDAD" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ALERTASMOROSIDAD" MODIFY ("DIAS_MORA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ALERTASMOROSIDAD" ADD PRIMARY KEY ("ID_ALERTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADOSFINANCIEROS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ESTADOSFINANCIEROS" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTADOSFINANCIEROS" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTADOSFINANCIEROS" ADD PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATRICULAS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MATRICULAS" MODIFY ("ID_MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MATRICULAS" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MATRICULAS" MODIFY ("AÑO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MATRICULAS" MODIFY ("CUATRIMESTRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MATRICULAS" MODIFY ("MONTO_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MATRICULAS" ADD PRIMARY KEY ("ID_MATRICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAGOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PAGOS" MODIFY ("ID_PAGO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PAGOS" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PAGOS" MODIFY ("FECHA_PAGO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PAGOS" MODIFY ("MONTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PAGOS" ADD PRIMARY KEY ("ID_PAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ALERTASMOROSIDAD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ALERTASMOROSIDAD" ADD CONSTRAINT "FK_ALERTAS_EST" FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "SYSTEM"."ESTUDIANTES" ("ID_ESTUDIANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTADOSFINANCIEROS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ESTADOSFINANCIEROS" ADD CONSTRAINT "FK_ESTFIN_EST" FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "SYSTEM"."ESTUDIANTES" ("ID_ESTUDIANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATRICULAS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MATRICULAS" ADD CONSTRAINT "FK_MATRICULAS_EST" FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "SYSTEM"."ESTUDIANTES" ("ID_ESTUDIANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAGOS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PAGOS" ADD CONSTRAINT "FK_PAGOS_EST" FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "SYSTEM"."ESTUDIANTES" ("ID_ESTUDIANTE") ENABLE;
